### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by xcoulon** [cescoffier/vertx-microservices-examples#4]
Hello,

I get the following compilation errors after running `mvn clean verify` at the root of the project, as explained in the README.md file:

`
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5:compile (default-compile) on project aggregation-http-a: Compilation failure: Compilation failure:
[ERROR] /Users/xcoulon/code/vertx-microservices-examples/aggregation-http/A/src/main/java/io/vertx/microservices/A.java:[104,62] incompatible types: io.vertx.core.json.JsonObject cannot be converted to io.vertx.ext.discovery.Record
[ERROR] /Users/xcoulon/code/vertx-microservices-examples/aggregation-http/A/src/main/java/io/vertx/microservices/A.java:[115,62] incompatible types: io.vertx.core.json.JsonObject cannot be converted to io.vertx.ext.discovery.Record
[ERROR] /Users/xcoulon/code/vertx-microservices-examples/aggregation-http/A/src/main/java/io/vertx/microservices/A.java:[126,62] incompatible types: io.vertx.core.json.JsonObject cannot be converted to io.vertx.ext.discovery.Record
[ERROR] /Users/xcoulon/code/vertx-microservices-examples/aggregation-http/A/src/main/java/io/vertx/microservices/A.java:[134,12] method executeWithFallback in interface io.vertx.ext.circuitbreaker.CircuitBreaker cannot be applied to given types;
[ERROR] required: io.vertx.core.Handler<io.vertx.core.Future<T>>,java.util.function.Function<java.lang.Throwable,T>
[ERROR] found: (circuitFu[...]; } },(v)->{ if [...]"); }
[ERROR] reason: cannot infer type-variable(s) T
[ERROR] (argument mismatch; bad return type in lambda expression
[ERROR] missing return value)
`

Not sure if this can help, but I noticed that I pulled a lot of `io.vertx:vertx-...-3.3-SNAPSHOT` maven dependencies, so maybe some API changed ?

**Comment by cescoffier** [comment]
Yes a _couple_ of API changes, let me update the code.

**Comment by xcoulon** [comment]
great, thanks @cescoffier !

**Comment by cescoffier** [comment]
Done !

**Comment by cescoffier** [comment]
BTW, 3.3.0 is going to be released, once there, the API will be stable.

**Comment by xcoulon** [comment]
ok, great, thanks for that very quick fix !

**Comment by xcoulon** [comment]
`BUILD SUCCESS` :-)
