### ISSUE TITLE
Discovering working but not the example

### ISSUE THREAD

**Issue by davidaparicio** [cescoffier/vertx-microservices-examples#6]
Hi @cescoffier !

The example is working well in my local machine. Before to test to Kubernetes (Google Compute Engine), I made containers and I launched, locally, them with docker-compose. The logs and the discovery page seem everything is working well but the main application doesn't work.... Do you have a idea, why is it not working ? Because unfortunately, I have any clue..

![screen shot 2016-09-08 at 3 08 37 pm](https://cloud.githubusercontent.com/assets/809982/18350455/58bfc1ec-75d6-11e6-8c1a-d25138f5d964.png)

The discovery page:
![screen shot 2016-09-08 at 3 08 20 pm](https://cloud.githubusercontent.com/assets/809982/18350449/51cc2312-75d6-11e6-94d8-4e18f639318f.png)

The docker-compose log, and Hazelcast discovery:
![screen shot 2016-09-08 at 3 08 54 pm](https://cloud.githubusercontent.com/assets/809982/18350457/5cd2782e-75d6-11e6-91e6-13cec5197f13.png)

Finally the circuit-breaker:
![screen shot 2016-09-08 at 3 14 31 pm](https://cloud.githubusercontent.com/assets/809982/18350605/f7c3a560-75d6-11e6-8d43-fd23c4d8ca56.png)

Best regards,
David

**Comment by davidaparicio** [comment]
You can find the code in my repository: https://github.com/davidaparicio/vertx-microservices-examples

**Comment by cescoffier** [comment]
Hi, yes, I think I have an idea.

The service are exposed on localhost:808x, which in your environment may be an issue because they are not deployed on the same machine.

**Comment by davidaparicio** [comment]
So true, I have not even seen this ineptitude -_-'

Now, I have a question about the same system under Kubernetes.. I think this system of Discover is the best way to communicate between containers/hosts on the cloud (like Google Compute Engine). It is the same like Openshift ? (:

Because, my last step will be to use Kubernetes Cluster Federation ^^

**Comment by cescoffier** [comment]
We provide an extension to the discovery service to use Kubernetes services and import them "automatically" - check http://vertx.io/docs/vertx-service-discovery-bridge-kubernetes/java/

With this bridge, you don't have to _publish_ your services as you need to declare them into Kubernetes. The bridge will then retrieve the services from Kubernetes.

**Comment by davidaparicio** [comment]
When I follow the "Run the demos in Openshift Origin (v3)" chapter (with the help of the jimmidyson/minishift), the compilation
`mvn clean package docker:build fabric8:json fabric8:apply -Popenshift`
fails.

```
[WARNING] The assembly descriptor contains a filesystem-root relative reference, which is not cross platform compatible /
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.529 s
[INFO] Finished at: 2016-10-10T15:17:50+02:00
[INFO] Final Memory: 21M/214M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.14.2:build (default-cli) on project aggregation-http: Failed to create assembly for docker image: Error adding file to archive: /Users/david/src/github.com/cescoffier/vertx-microservices-examples/aggregation-http/target/aggregation-http-1.0-SNAPSHOT-fat.jar with mode dir -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:docker-maven-plugin:0.14.2:build (default-cli) on project aggregation-http: Failed to create assembly for docker image: Error adding file to archive: /Users/david/src/github.com/cescoffier/vertx-microservices-examples/aggregation-http/target/aggregation-http-1.0-SNAPSHOT-fat.jar with mode dir
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create assembly for docker image: Error adding file to archive: /Users/david/src/github.com/cescoffier/vertx-microservices-examples/aggregation-http/target/aggregation-http-1.0-SNAPSHOT-fat.jar with mode dir
```

**Comment by davidaparicio** [comment]
Hi @cescoffier !

I followed the "Run the demos in Openshift Origin (v3)" chapter

Instead of 

```
docker rm origin
sudo docker run -d --name "origin" \
        --privileged --pid=host --net=host \
        -v /:/rootfs:ro -v /var/run:/var/run:rw -v /sys:/sys -v /var/lib/docker:/var/lib/docker:rw \
        -v /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes \
        openshift/origin start
docker logs -f origin
```

I used `jimmidyson/minishift`

I run `mvn clean package docker:build fabric8:json fabric8:apply -Popenshift` without problem.

The dashboard is in the same as yours (I grouped A and B only for the screenshot)

![screen shot 2016-10-10 at 4 24 07 pm](https://cloud.githubusercontent.com/assets/809982/19240663/b35fbba4-8f0b-11e6-8575-ed5f165bcee1.png)

But the discovery isn't working (bug with Kubernetes) 

![screen shot 2016-10-10 at 4 26 09 pm](https://cloud.githubusercontent.com/assets/809982/19240761/2157c0f2-8f0c-11e6-8821-b69c787993a4.png)

```
Oct 10, 2016 2:13:13 PM io.vertx.servicediscovery.kubernetes.KubernetesServiceImporter
INFO: Kubernetes discovery configured for namespace: vertx-microservice-example-aggregation-http
Oct 10, 2016 2:13:13 PM io.vertx.servicediscovery.kubernetes.KubernetesServiceImporter
INFO: Kubernetes url: https://172.30.0.1:443
Oct 10, 2016 2:13:13 PM io.vertx.servicediscovery.kubernetes.KubernetesServiceImporter
INFO: Kubernetes discovery: Bearer Token { eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ2ZXJ0eC1taWNyb3NlcnZpY2UtZXhhbXBsZS1hZ2dyZWdhdGlvbi1odHRwIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tejNsam4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjkyNDYxMDdjLThlZjMtMTFlNi04MWJiLTYyZDM5MWNkMTNkZSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDp2ZXJ0eC1taWNyb3NlcnZpY2UtZXhhbXBsZS1hZ2dyZWdhdGlvbi1odHRwOmRlZmF1bHQifQ.M-oLdMaBNKxvPpdzDOov5l-0ob49FajvEFnuzXhmFe3Tlv59qnN8bDPjfIUNDvmvQlbVMHGsRx9HwHj9RrFswe-gjGpIy1uRaynQgYOyH1OJXc8uKvAgEgrZ6dRfVJ2o9qevat0J8M3Pfu_bClBmmEpoFOBfSyXgH9_z7Iuw6YeGsvh2JVP-obwyT1JwJq-n6n0zCD43oUvrMRlaEmS3R9lG5kaGZN2azcHwAHNrkn3SOzX32KOqYsmlosZDRvip4MBbGDg8dkqxYSHEVWQkKgnHOMfyoZXHkbqF_qvlyYveL5XnifRKGj7oUaUw4wDXRaYQNs-ZAkvll27Mf6hQZA }
Oct 10, 2016 2:13:13 PM io.vertx.servicediscovery.kubernetes.KubernetesServiceImporter
SEVERE: Error while interacting with kubernetes
```

What I have to do to resolve this?

Annexe:
I tested the service (like, http://c-vertx-microservice-example-aggregation-http.192.168.99.102.xip.io/?name=test it's working).

![screen shot 2016-10-10 at 4 26 32 pm](https://cloud.githubusercontent.com/assets/809982/19240783/367a4018-8f0c-11e6-8909-688477b59068.png)

![screen shot 2016-10-10 at 4 26 41 pm](https://cloud.githubusercontent.com/assets/809982/19240791/3bfa74cc-8f0c-11e6-978e-cf92758b844f.png)

**Comment by cescoffier** [comment]
You need to add slf4j-api as a dependency to all projects.

**Comment by davidaparicio** [comment]
Okay, thanks a lot @cescoffier !!
